### ISSUE TITLE
LICENSE file missing

### ISSUE THREAD

**Issue by eigenpunk** [dab-bot/ComfyUI-SDXL-DiscordBot#12]
this repository does not appear to have any public declaration of a license, so it is unclear whether use, modification, or redistribution of this repository and its contents is legally permitted.

from [choosealicense](https://choosealicense.com/no-permission/):
> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.

if you could kindly [select](https://choosealicense.com/) and add a license to this repository (in a LICENSE file or in the README.md) so that its users have clarity on whether/how they may use/modify/redistribute this work, it'd be much appreciated! :)

**Comment by aaronfisher-code** [comment]
Thanks for the heads up! I've added the license to the repo now
